/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/rockie/wpi_sample_return_challenge_2015/test_indigo_workspace/src/thresholding/srv/ProcessImage.srv
 *
 */


#ifndef THRESHOLDING_MESSAGE_PROCESSIMAGE_H
#define THRESHOLDING_MESSAGE_PROCESSIMAGE_H

#include <ros/service_traits.h>


#include <thresholding/ProcessImageRequest.h>
#include <thresholding/ProcessImageResponse.h>


namespace thresholding
{

struct ProcessImage
{

typedef ProcessImageRequest Request;
typedef ProcessImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessImage
} // namespace thresholding


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::thresholding::ProcessImage > {
  static const char* value()
  {
    return "c3e760ca42cb04034d3ea4bedb8b4008";
  }

  static const char* value(const ::thresholding::ProcessImage&) { return value(); }
};

template<>
struct DataType< ::thresholding::ProcessImage > {
  static const char* value()
  {
    return "thresholding/ProcessImage";
  }

  static const char* value(const ::thresholding::ProcessImage&) { return value(); }
};


// service_traits::MD5Sum< ::thresholding::ProcessImageRequest> should match 
// service_traits::MD5Sum< ::thresholding::ProcessImage > 
template<>
struct MD5Sum< ::thresholding::ProcessImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::thresholding::ProcessImage >::value();
  }
  static const char* value(const ::thresholding::ProcessImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::thresholding::ProcessImageRequest> should match 
// service_traits::DataType< ::thresholding::ProcessImage > 
template<>
struct DataType< ::thresholding::ProcessImageRequest>
{
  static const char* value()
  {
    return DataType< ::thresholding::ProcessImage >::value();
  }
  static const char* value(const ::thresholding::ProcessImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::thresholding::ProcessImageResponse> should match 
// service_traits::MD5Sum< ::thresholding::ProcessImage > 
template<>
struct MD5Sum< ::thresholding::ProcessImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::thresholding::ProcessImage >::value();
  }
  static const char* value(const ::thresholding::ProcessImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::thresholding::ProcessImageResponse> should match 
// service_traits::DataType< ::thresholding::ProcessImage > 
template<>
struct DataType< ::thresholding::ProcessImageResponse>
{
  static const char* value()
  {
    return DataType< ::thresholding::ProcessImage >::value();
  }
  static const char* value(const ::thresholding::ProcessImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THRESHOLDING_MESSAGE_PROCESSIMAGE_H
