// Generated by gencpp from file thresholding/ProcessImage.msg
// DO NOT EDIT!


#ifndef THRESHOLDING_MESSAGE_PROCESSIMAGE_H
#define THRESHOLDING_MESSAGE_PROCESSIMAGE_H

#include <ros/service_traits.h>


#include <thresholding/ProcessImageRequest.h>
#include <thresholding/ProcessImageResponse.h>


namespace thresholding
{

struct ProcessImage
{

typedef ProcessImageRequest Request;
typedef ProcessImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessImage
} // namespace thresholding


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::thresholding::ProcessImage > {
  static const char* value()
  {
    return "c3e760ca42cb04034d3ea4bedb8b4008";
  }

  static const char* value(const ::thresholding::ProcessImage&) { return value(); }
};

template<>
struct DataType< ::thresholding::ProcessImage > {
  static const char* value()
  {
    return "thresholding/ProcessImage";
  }

  static const char* value(const ::thresholding::ProcessImage&) { return value(); }
};


// service_traits::MD5Sum< ::thresholding::ProcessImageRequest> should match 
// service_traits::MD5Sum< ::thresholding::ProcessImage > 
template<>
struct MD5Sum< ::thresholding::ProcessImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::thresholding::ProcessImage >::value();
  }
  static const char* value(const ::thresholding::ProcessImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::thresholding::ProcessImageRequest> should match 
// service_traits::DataType< ::thresholding::ProcessImage > 
template<>
struct DataType< ::thresholding::ProcessImageRequest>
{
  static const char* value()
  {
    return DataType< ::thresholding::ProcessImage >::value();
  }
  static const char* value(const ::thresholding::ProcessImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::thresholding::ProcessImageResponse> should match 
// service_traits::MD5Sum< ::thresholding::ProcessImage > 
template<>
struct MD5Sum< ::thresholding::ProcessImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::thresholding::ProcessImage >::value();
  }
  static const char* value(const ::thresholding::ProcessImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::thresholding::ProcessImageResponse> should match 
// service_traits::DataType< ::thresholding::ProcessImage > 
template<>
struct DataType< ::thresholding::ProcessImageResponse>
{
  static const char* value()
  {
    return DataType< ::thresholding::ProcessImage >::value();
  }
  static const char* value(const ::thresholding::ProcessImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THRESHOLDING_MESSAGE_PROCESSIMAGE_H
