/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PCComms.h"
#include "PCComms_SPI_UART.h"
#include "PCComms_PINS.h"
#include "PCComms_SPI_UART_PVT.h"
#include "PCComms_PVT.h"
#include "PCComms_BOOT.h"
#include "Limit_LT.h"
#include "Limit_LT_aliases.h"
#include "MotorControl2EN.h"
#include "MotorControl2EN_aliases.h"
#include "MotorControl4EN.h"
#include "MotorControl4EN_aliases.h"
#include "MotorControl3EN.h"
#include "MotorControl3EN_aliases.h"
#include "MotorComms.h"
#include "MotorComms_SPI_UART.h"
#include "MotorComms_PINS.h"
#include "MotorComms_SPI_UART_PVT.h"
#include "MotorComms_PVT.h"
#include "MotorComms_BOOT.h"
#include "MotorControl1EN.h"
#include "MotorControl1EN_aliases.h"
#include "MotorControl5EN.h"
#include "MotorControl5EN_aliases.h"
#include "FPGA_EN.h"
#include "FPGA_EN_aliases.h"
#include "Red.h"
#include "Red_aliases.h"
#include "Yellow.h"
#include "Yellow_aliases.h"
#include "Green.h"
#include "Green_aliases.h"
#include "Timer_1.h"
#include "OpenPressure.h"
#include "OpenPressure_aliases.h"
#include "OpenExhaust.h"
#include "OpenExhaust_aliases.h"
#include "ClosePressure.h"
#include "ClosePressure_aliases.h"
#include "CloseExhaust.h"
#include "CloseExhaust_aliases.h"
#include "Limit_LS.h"
#include "Limit_LS_aliases.h"
#include "Limit_RT.h"
#include "Limit_RT_aliases.h"
#include "Limit_RS.h"
#include "Limit_RS_aliases.h"
#include "Steering_Register.h"
#include "Pause_Register.h"
#include "PCComms_SCBCLK.h"
#include "PCComms_tx.h"
#include "PCComms_tx_aliases.h"
#include "PCComms_SCB_IRQ.h"
#include "PCComms_rx.h"
#include "PCComms_rx_aliases.h"
#include "MotorComms_SCBCLK.h"
#include "MotorComms_tx.h"
#include "MotorComms_tx_aliases.h"
#include "MotorComms_rx.h"
#include "MotorComms_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

