/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Bootloadable_1.h>
#include <phiB_In.h>
#include <phiB_In_aliases.h>
#include <phiA_In.h>
#include <phiA_In_aliases.h>
#include <phiA_Out.h>
#include <phiA_Out_aliases.h>
#include <Clock_1.h>
#include <phiA_Out_1.h>
#include <phiA_Out_1_aliases.h>
#include <phiA_In_1.h>
#include <phiA_In_1_aliases.h>
#include <phiB_In_1.h>
#include <phiB_In_1_aliases.h>
#include <Pin_3.h>
#include <Pin_3_aliases.h>
#include <Pin_4.h>
#include <Pin_4_aliases.h>
#include <phiA_Out_2.h>
#include <phiA_Out_2_aliases.h>
#include <phiA_In_2.h>
#include <phiA_In_2_aliases.h>
#include <phiB_In_2.h>
#include <phiB_In_2_aliases.h>
#include <Pin_5.h>
#include <Pin_5_aliases.h>
#include <Pin_6.h>
#include <Pin_6_aliases.h>
#include <phiA_Out_3.h>
#include <phiA_Out_3_aliases.h>
#include <phiA_In_3.h>
#include <phiA_In_3_aliases.h>
#include <phiB_In_3.h>
#include <phiB_In_3_aliases.h>
#include <Pin_7.h>
#include <Pin_7_aliases.h>
#include <Pin_8.h>
#include <Pin_8_aliases.h>
#include <Counter_1.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

