/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/rockie/wpi_sample_return_challenge_2015/test_indigo_workspace/src/object_recognition/srv/Image.srv
 *
 */


#ifndef OBJECT_RECOGNITION_MESSAGE_IMAGE_H
#define OBJECT_RECOGNITION_MESSAGE_IMAGE_H

#include <ros/service_traits.h>


#include <object_recognition/ImageRequest.h>
#include <object_recognition/ImageResponse.h>


namespace object_recognition
{

struct Image
{

typedef ImageRequest Request;
typedef ImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Image
} // namespace object_recognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_recognition::Image > {
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::object_recognition::Image&) { return value(); }
};

template<>
struct DataType< ::object_recognition::Image > {
  static const char* value()
  {
    return "object_recognition/Image";
  }

  static const char* value(const ::object_recognition::Image&) { return value(); }
};


// service_traits::MD5Sum< ::object_recognition::ImageRequest> should match 
// service_traits::MD5Sum< ::object_recognition::Image > 
template<>
struct MD5Sum< ::object_recognition::ImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_recognition::Image >::value();
  }
  static const char* value(const ::object_recognition::ImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_recognition::ImageRequest> should match 
// service_traits::DataType< ::object_recognition::Image > 
template<>
struct DataType< ::object_recognition::ImageRequest>
{
  static const char* value()
  {
    return DataType< ::object_recognition::Image >::value();
  }
  static const char* value(const ::object_recognition::ImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_recognition::ImageResponse> should match 
// service_traits::MD5Sum< ::object_recognition::Image > 
template<>
struct MD5Sum< ::object_recognition::ImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_recognition::Image >::value();
  }
  static const char* value(const ::object_recognition::ImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_recognition::ImageResponse> should match 
// service_traits::DataType< ::object_recognition::Image > 
template<>
struct DataType< ::object_recognition::ImageResponse>
{
  static const char* value()
  {
    return DataType< ::object_recognition::Image >::value();
  }
  static const char* value(const ::object_recognition::ImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_RECOGNITION_MESSAGE_IMAGE_H
