// Generated by gencpp from file object_recognition/ImageRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_RECOGNITION_MESSAGE_IMAGEREQUEST_H
#define OBJECT_RECOGNITION_MESSAGE_IMAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_recognition
{
template <class ContainerAllocator>
struct ImageRequest_
{
  typedef ImageRequest_<ContainerAllocator> Type;

  ImageRequest_()
    : path()  {
    }
  ImageRequest_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;




  typedef boost::shared_ptr< ::object_recognition::ImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_recognition::ImageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageRequest_

typedef ::object_recognition::ImageRequest_<std::allocator<void> > ImageRequest;

typedef boost::shared_ptr< ::object_recognition::ImageRequest > ImageRequestPtr;
typedef boost::shared_ptr< ::object_recognition::ImageRequest const> ImageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_recognition::ImageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_recognition::ImageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_recognition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_recognition::ImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_recognition::ImageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_recognition::ImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_recognition::ImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_recognition::ImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_recognition::ImageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_recognition::ImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::object_recognition::ImageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d00cd540af97efeULL;
  static const uint64_t static_value2 = 0xb6b1589112fab63eULL;
};

template<class ContainerAllocator>
struct DataType< ::object_recognition::ImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_recognition/ImageRequest";
  }

  static const char* value(const ::object_recognition::ImageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_recognition::ImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path\n\
";
  }

  static const char* value(const ::object_recognition::ImageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_recognition::ImageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ImageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_recognition::ImageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_recognition::ImageRequest_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_RECOGNITION_MESSAGE_IMAGEREQUEST_H
