// Generated by gencpp from file object_recognition/Image.msg
// DO NOT EDIT!


#ifndef OBJECT_RECOGNITION_MESSAGE_IMAGE_H
#define OBJECT_RECOGNITION_MESSAGE_IMAGE_H

#include <ros/service_traits.h>


#include <object_recognition/ImageRequest.h>
#include <object_recognition/ImageResponse.h>


namespace object_recognition
{

struct Image
{

typedef ImageRequest Request;
typedef ImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Image
} // namespace object_recognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_recognition::Image > {
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::object_recognition::Image&) { return value(); }
};

template<>
struct DataType< ::object_recognition::Image > {
  static const char* value()
  {
    return "object_recognition/Image";
  }

  static const char* value(const ::object_recognition::Image&) { return value(); }
};


// service_traits::MD5Sum< ::object_recognition::ImageRequest> should match 
// service_traits::MD5Sum< ::object_recognition::Image > 
template<>
struct MD5Sum< ::object_recognition::ImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_recognition::Image >::value();
  }
  static const char* value(const ::object_recognition::ImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_recognition::ImageRequest> should match 
// service_traits::DataType< ::object_recognition::Image > 
template<>
struct DataType< ::object_recognition::ImageRequest>
{
  static const char* value()
  {
    return DataType< ::object_recognition::Image >::value();
  }
  static const char* value(const ::object_recognition::ImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_recognition::ImageResponse> should match 
// service_traits::MD5Sum< ::object_recognition::Image > 
template<>
struct MD5Sum< ::object_recognition::ImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_recognition::Image >::value();
  }
  static const char* value(const ::object_recognition::ImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_recognition::ImageResponse> should match 
// service_traits::DataType< ::object_recognition::Image > 
template<>
struct DataType< ::object_recognition::ImageResponse>
{
  static const char* value()
  {
    return DataType< ::object_recognition::Image >::value();
  }
  static const char* value(const ::object_recognition::ImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_RECOGNITION_MESSAGE_IMAGE_H
