TrajectoryPlannerROS:
  max_vel_x: 0.5 # temporary until we really know what we want
  min_vel_x: 0.05 # we should test this
  max_rotation_vel: 1.0
  min_in_place_rotational_vel: 0.1

  acc_lim_theta: 3
  acc_lim_x: 3
  acc_lim_y: 3
  meter_scoring: true
  holonomic_robot: false
