obstacle_range: 6
raytrace_range: 8
footprint: [[0.889, 0.3048], [0.889, -0.3048], [-0.4572, -0.3048], [-0.4572, 0.3048]]
inflation_radius: 1
observation_sources: point_cloud_sensor

# not sure if this is right
point_cloud_sensor: {sensor_frame: base_link, data_type: PointCloud2, topic: /planner_cloud, marking: true, clearing: true}
transform_tolerance: 5
