global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.5 # what exactly is this update rate?
  static_map: false
  rolling_window: false
  map_type: costmap
  width: 200.0
  height: 200.0
  origin_x: -100.0
  origin_y: -100.0
  resolution: 0.3
