local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 0.5 # need to look this up
  publish_frequency: 0.5 # yeah no idea
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  origin_x: -5.0
  origin_y: -5.0
  resolution: 0.05
  map_type: costmap
  min_obstacle_height: -9999.0
  max_obstacle_height: 9999.0
  meter_scoring: true
