frame_id: base_link
odom_frame_id: odom

Odom:
  # 0=SURF 1=SIFT 2=ORB 3=FAST/FREAK 4=FAST/BRIEF 5=GFTT/FREAK 6=GFTT/BRIEF
  # 7=BRISK
  FeatureType: 6 # default GFTT/BRIEF
  Strategy: "0" # 0: bag of words 1: optical flow
  InlierDistance: "0.1"
  MinInliers: "8"
  #RoiRatios: "0.03 0.03 0.04 0.04"
  MaxDepth: "10"
  FillInfoData: "true"

OdomBow:
  NNDR: "0.8"

GFTT:
  MaxCorners: "500"
  MinDistance: "5"
